//! `OpenAPI` spec assembly — serves `/api/v1/openapi.json`.

use utoipa::OpenApi;

#[allow(clippy::needless_for_each)] // generated by utoipa derive macro
#[derive(OpenApi)]
#[openapi(
    info(
        title = "multilinguarr",
        description = "Multi-language audio enforcement for the *arr media stack",
        license(name = "MIT"),
        version = env!("CARGO_PKG_VERSION"),
    ),
    paths(
        // Languages
        super::languages::list,
        super::languages::get,
        super::languages::create,
        super::languages::update,
        super::languages::delete,
        // Instances
        super::instances::list,
        super::instances::get,
        super::instances::create,
        super::instances::update,
        super::instances::delete,
        // Config
        super::config::get,
        super::config::update,
        // Setup
        super::setup::status,
        super::setup::complete,
        // Jobs
        super::jobs::list,
        super::jobs::get,
        super::jobs::queue_stats,
        super::jobs::retry,
        super::jobs::reprocess_all,
        // Admin
        super::regenerate::trigger,
        // Schema
        super::schema::languages_schema,
        super::schema::instances_schema,
        super::schema::config_schema,
        // Monitoring
        crate::webhook::server::health,
        crate::observability::metrics_handler,
    ),
    components(schemas(
        super::languages::LanguageResponse,
        super::languages::LanguageDefinitionDto,
        super::languages::CreateLanguageRequest,
        super::instances::InstanceDto,
        super::config::GeneralConfigDto,
        super::setup::SetupStatus,
        super::jobs::JobDto,
        crate::queue::QueueStats,
        crate::reconcile::RegenerateResult,
        crate::reconcile::RegenerateAction,
    )),
    tags(
        (name = "languages", description = "Language definitions"),
        (name = "instances", description = "Arr instance configuration"),
        (name = "config", description = "General configuration"),
        (name = "setup", description = "First-run setup flow"),
        (name = "jobs", description = "Job queue visibility"),
        (name = "admin", description = "Administrative operations"),
        (name = "schema", description = "Self-documenting field definitions"),
        (name = "monitoring", description = "Health and metrics"),
    ),
    security(
        ("api_key" = [])
    ),
    modifiers(&SecurityAddon)
)]
#[derive(Debug)]
pub struct ApiDoc;

/// Generate the spec as a JSON string — used by the docs build
/// script to create `docs/public/openapi.json`.
///
/// # Panics
///
/// Panics if the `OpenAPI` spec fails to serialize to JSON.
#[must_use]
pub fn spec_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .expect("openapi serialization")
}

/// Adds X-Api-Key security scheme to the spec.
struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "api_key",
            utoipa::openapi::security::SecurityScheme::ApiKey(
                utoipa::openapi::security::ApiKey::Header(
                    utoipa::openapi::security::ApiKeyValue::new("X-Api-Key"),
                ),
            ),
        );
    }
}
